//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlazorAppDataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameRoundUserResult
    {
        public int UserID { get; set; }
        public int GameRoundID { get; set; }
        public int TriviaResult { get; set; }
        public int GameResult { get; set; }
    
        public virtual GameRound GameRound { get; set; }
        public virtual User User { get; set; }
    }
}
