//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlazorAppDataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameRound
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GameRound()
        {
            this.GameRoundUserResults = new HashSet<GameRoundUserResult>();
        }
    
        public int GameRoundID { get; set; }
        public Nullable<int> GameID { get; set; }
        public Nullable<int> Wager { get; set; }
        public int TriviaQuestionID { get; set; }
    
        public virtual Game Game { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GameRoundUserResult> GameRoundUserResults { get; set; }
        public virtual TriviaQuestion TriviaQuestion { get; set; }
    }
}
