//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlazorAppDataLayer.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BlazorCasinoAppEntities : DbContext
    {
        public BlazorCasinoAppEntities()
            : base("name=BlazorCasinoAppEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChatMessage> ChatMessages { get; set; }
        public virtual DbSet<Chatroom> Chatrooms { get; set; }
        public virtual DbSet<GameRound> GameRounds { get; set; }
        public virtual DbSet<GameRoundUserResult> GameRoundUserResults { get; set; }
        public virtual DbSet<Game> Games { get; set; }
        public virtual DbSet<TriviaQuestion> TriviaQuestions { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
